### ISSUE TITLE
English word problem

### ISSUE THREAD

**Issue by liuqingkai007** [smalldirector/solr-multilangs-analyzer#2]
Hello there! In search of the English word, even made a word. How is this going?
![1](https://cloud.githubusercontent.com/assets/3980343/6839039/c49b5354-d39d-11e4-8919-d683f731399e.png)

**Comment by smalldirector** [comment]
In the query process, this plugin will add en|zh-cn|ja prefix automatically.
So the result will show all tokens generated by three languages' analyzer.

**Comment by liuqingkai007** [comment]
hi!  
I have a lot of doubts, when entering a word, why not check the word of the language, and then make the appropriate word?

**Comment by smalldirector** [comment]
The following is some reasons:
* If it's just a simple word, it's no meaning for language detection.
* This simple word can be included in a article which is a different language text, so you can say this word is in which language text.
